### PR TITLE
Fix Pageout 0 on Safari

### PR DESCRIPTION
**Pull request by Superpencil**
https://github.com/blivesta/animsition/issues/55

### CODE REVIEW

**Comment by blivesta** [comment]
Thanks for the pull request! 
Please wait because we have an update working on a branch v4.0.0. #50

**Comment by Superpencil** [comment]
OK! :D

**Comment by blivesta** [comment]
I still have not been able to find this problem.🐞
Don't cause problems in `pageIn`?

**Comment by Superpencil** [comment]
No, animsition-enabled links do not do anything at all if the fadeOut is set to 0 on Safari :)

**Comment by blivesta** [comment]
Thanks :D

**Comment by Superpencil** [comment]
:dancers:

**Pull request merged**
