### PR TITLE
Provide feedback when element doesn't exist on page instead of "Anims…

### PR DESCRIPTION
**Pull request by brianmontanaweb**
Provide feedback when element doesn't exist on page instead of "Animsition does not support this browser."

### CODE REVIEW

**Comment by blivesta** [comment]
Thanks for the pull request! 
I think it is better not to destroy even if the Element does not exist in the page.
Example of if you want to add a log.
```js
if(!support || !this.length){
  // If do not have a console object to object window
  if (!('console' in window)) {
    window.console = {};
    window.console.log = function(str){return str};
  }
  if(!this.length){
    console.log("Element does not exist on page.");
  } else {
    console.log("Animsition does not support this browser.");
    return methods.destroy.call( this );
  }
}
```

**Comment by blivesta** [comment]
my mistake. It has been destroy when it does not exist even now.😱
```js
if(!support || !this.length){
  // If do not have a console object to object window
  if (!('console' in window)) {
    window.console = {};
    window.console.log = function(str){return str};
  }
  if(!this.length){
    console.log("Animsition: Element does not exist on page.");
  }
  if(!support){
    console.log("Animsition: Does not support this browser.");
  }
  return methods.destroy.call( this );
}
```

**Comment by brianmontanaweb** [comment]
Nice, much better approach :+1:

**Comment by blivesta** [comment]
Thanks :)
`options.unSupportCss : []` 
The return value of this case `support` is `true`. so I added a condition for this.
https://github.com/blivesta/animsition/blob/master/src/js/animsition.js#L101-L106

```js
if(!support && options.unSupportCss.length > 0){
  if(!support || !this.length){
   ...
 }
} 
```

**Comment by brianmontanaweb** [comment]
Makes sense if the user decides to set null or an empty array, but is that anticipating too much? Can't we just respond with a general "options" require a value?

**Comment by blivesta** [comment]
There are people who are using that option is empty, we think it is better not now change it.
https://github.com/blivesta/animsition/issues/44#issuecomment-121600496 

Also in the future we believe also additional options.
https://gist.github.com/blivesta/c3cfc864b3ab2afc7470

**Comment by brianmontanaweb** [comment]
Ah, good point! Making the update.

**Comment by blivesta** [comment]
Thanks!

**Pull request merged**
